//Variables for helps
//TODO:This must be moved into help resource file
var help = {
  "short": {
      "Key Partners":"Who are your key partners/suppliers?\n What are the" +
           " motivations for the partnerships?"
    , "Key Activities": "What key activities does your value proposition require?" +
            "\n What activities are important the most in distribution channels, customer relationships, revenue stream..?"
    , "Key Resources": " What key resources does your value proposition require?\n  What resources are important the most in distribution channels, customer relationships, revenue stream..?"
    , "Value Propositions": "What core value do you deliver to the customer?\n Which customer needs are you satisfying?"
    , "Customer Relationships": "What relationship that the target customer expects you to establish?\n  How can you integrate that into your business in terms of cost and format?"
    , "Customer Segments": " Which classes are you creating values for?\n  Who is your most important customer?"
    , "Channels": "What relationship that the target customer expects you to establish?\n  How can you integrate that into your business in terms of cost and format?"
    , "Cost Structure": " What are the most cost in your business?\n  Which key resources/ activities are most expensive?"
    , "Revenue Streams": " For what value are your customers willing to pay?\n  What and how do they recently pay? How would they prefer to pay?\n  How much does every revenue stream contribute to the overall revenues?"
  },
  "more": {
    "kp":"Key Partners"
  , "ka": "The most important activities in executing a company's value proposition. An example for Bic, the pen manufacturer, would be creating an efficient supply chain to drive down costs."
  , "kr": " The resources that are necessary to create value for the customer. They are considered an asset to a company, which are needed in order to sustain and support the business. These resources could be human, financial, physical and intellectual"
  , "vp": 'The collection of products and services a business offers to meet the needs of its customers. According to Osterwalder, (2004), a company\'s value proposition is what distinguishes itself from its competitors. The value proposition provides value through various elements such as newness, performance, customization, "getting the job done", design, brand/status, price, cost reduction, risk reduction, accessibility, and convenience/usability.'
  , "cr": " To ensure the survival and success of any businesses, companies must identify the type of relationship they want to create with their customer segments. Various forms of customer relationships include:\n  Personal Assistance: Assistance in a form of employee-customer interaction. Such assistance is performed either during sales, after sales, and/or both.\n  Dedicated Personal Assistance: The most intimate and hands on personal assistance where a sales representative is assigned to handle all the needs and questions of a special set of clients.\n  Self Service: The type of relationship that translates from the indirect interaction between the company and the clients. Here, an organization provides the tools needed for the customers to serve themselves easily and effectively.\n  Automated Services: A system similar to self-service but more personalized as it has the ability to identify individual customers and his/her preferences. An example of this would be Amazon.com making book suggestion based on the characteristics of the previous book purchased.\n  Communities: Creating a community allows for a direct interaction among different clients and the company. The community platform produces a scenario where knowledge can be shared and problems are solved between different clients.\n  Co-creation: A personal relationship is created through the customer's direct input in the final outcome of the company's products/services."
  , "cs": 'To build an effective business model, a company must identify which customers it tries to serve. Various sets of customers can be segmented based on the different needs and attributes to ensure appropriate implementation of corporate strategy meets the characteristics of selected group of clients. The different types of customer segments include:\n Mass Market: There is no specific segmentation for a company that follows the Mass Market element as the organization displays a wide view of potential clients. e.g. Car\n   Niche Market: Customer segmentation based on specialized needs and characteristics of its clients. e.g. Rolex\n Segmented: A company applies additional segmentation within existing customer segment. In the segmented situation, the business may further distinguish its clients based on gender, age, and/or income.\n   Diversify: A business serves multiple customer segments with different needs and characteristics.\n Multi-Sided Platform / Market: For a smooth day-to-day business operation, some companies will serve mutually dependent customer segment. A credit card company will provide services to credit card holders while simultaneously assisting merchants who accept those credit cards.'
  , "c": "A company can deliver its value proposition to its targeted customers through different channels. Effective channels will distribute a companyÎÎs value proposition in ways that are fast, efficient and cost effective. An organization can reach its clients either through its own channels (store front), partner channels (major distributors), or a combination of both."
  , "ct": "Cost Structure: This describes the most important monetary consequences while operating under different business models. A company's DOC.\n  Classes of Business Structures:\n  Cost-Driven - This business model focuses on minimizing all costs and having no frills. e.g. Low cost airlines\n  Value-Driven - Less concerned with cost, this business model focuses on creating value for their products and services. e.g. Louis Vuitton, Rolex\n  Characteristics of Cost Structures:\n  Fixed Costs - Costs are unchanged across different applications. e.g. salary, rent\n  Variable Costs - These costs vary depending on the amount of production of goods or services. e.g. music festivals\n  Economies of Scale - Costs go down as the amount of good are ordered or produced.\n  Economies of Scope - Costs go down due to incorporating other businesses which have a direct relation to the original product."
  , "rs": "The way a company makes income from each customer segment. Several ways to generate a revenue stream:\n  Asset Sale - (the most common type) Selling ownership rights to a physical good. e.g. retail corporations\n  Usage Fee - Money generated from the use of a particular service e.g. UPS\n  Subscription Fees - Revenue generated by selling a continuous service. e.g. Netflix\n  Lending/Leasing/Renting - Giving exclusive right to an asset for a particular period of time. e.g. Leasing a Car\n  Licensing - Revenue generated from charging for the use of a protected intellectual property.\n  Brokerage Fees - Revenue generated from an intermediate service between 2 parties. e.g. Broker selling a house for commission\n  Advertising - Revenue generated from charging fees for product advertising."
  }
};
